name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install WP-CLI
        run: curl -sO https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Run linting
        run: composer lint

      - name: Generate POT file
        run: bun run makepot

      - name: Build ZIP
        run: bun run zip

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/custom-plugin.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
